<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="HydraulicCylinder" Id="{3bf06456-7c7d-48f2-a9cc-e4b64f4dae07}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HydraulicCylinder
VAR_INPUT
	PressureBoreSide: LREAL;
	PressureRodSide: LREAL;
	AreaBoreSide: LREAL;
	AreaRodSide: LREAL;
	LoadForcePistonFL: LREAL;
	FrictionForce: LREAL;
	PistonMass: LREAL;
END_VAR
VAR_OUTPUT
	PistonAcceleration: LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
(* Outputs for Atomic SubSystem: '<Root>/HydraulicCylinder' *)
(* Outport: '<Root>/PistonAcceleration' incorporates:
 *  Gain: '<S1>/Gain1'
 *  Gain: '<S1>/Gain2'
 *  Product: '<S1>/Divide '
 *  Product: '<S1>/Product'
 *  Product: '<S1>/Product1'
 *  Sum: '<S1>/sum' *)
PistonAcceleration := (((((PressureBoreSide * AreaBoreSide) * 100000.0) - ((PressureRodSide * AreaRodSide) * 100000.0)) - FrictionForce) - LoadForcePistonFL) / PistonMass;
(* End of Outputs for SubSystem: '<Root>/HydraulicCylinder' *)

]]></ST>
    </Implementation>
    <LineIds Name="HydraulicCylinder">
      <LineId Id="3" Count="11" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>