<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="BulkModulus" Id="{d896bbce-21be-40f0-ade7-5314da5b1d90}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BulkModulus
VAR_INPUT
END_VAR
VAR_OUTPUT
	BulkModulus : LREAL := 10000E5;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="BulkModulus">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>