<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="ValveDynamics" Id="{bdd402cd-9955-422d-9429-c814b00ee090}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ValveDynamics
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ValveDynamics">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>