<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="P_Joy" Id="{5aaf6033-864c-4c13-9a1e-c92eedd8448a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Joy
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[XboxControl.joyLeft := INT_TO_LREAL(XboxControl.controller.LeftJoystickX)/32767.0;
]]></ST>
    </Implementation>
    <LineIds Name="P_Joy">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>