<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="UpdateEventTimestamptWithSystemTime" Id="{c4dbcab7-243b-4558-88c3-806cd52084ec}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventTimestamptWithSystemTime
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME;
	stFileTime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW => stFileTime.dwLowDateTime,
				timeHiDW => stFileTime.dwHighDateTime);
				
stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);]]></ST>
    </Implementation>
    <LineIds Name="UpdateEventTimestamptWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="17" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>